image: saisk026/ubuntu-docker:20.04

stages:
  - build
  - deploy

build_backend_dev:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  environment:
    name: development
  tags:
    - akeso-sk
  before_script:
    - echo "Building backend docker image"
    - export IMAGE_TAG="$(date +%Y%m%d%H%M)"
    - echo "IMAGE_TAG=${IMAGE_TAG}" > .env  # Ensure the IMAGE_TAG is saved in .env
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${ACR_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${ACR_USERNAME}" "${ACR_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - echo "Pushing the backend image to ACR with tag ${IMAGE_TAG}"
    - /kaniko/executor --context "${CI_PROJECT_DIR}" --dockerfile "${CI_PROJECT_DIR}/Dockerfile" --destination "${ACR_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_DEV_NAME}:${IMAGE_TAG}"
  artifacts:
    reports:
      dotenv: .env  # Upload the .env file as an artifact
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"


deploy_backend_dev:
  stage: deploy
  image: saisk026/kubectl:v2
  environment:
    name: development
  tags:
    - akeso-sk
  before_script:
    - echo "Deploying the backend application to Kubernetes"
    - mkdir -p ~/.kube
    - echo "$KUBECONFIG" | base64 -d > /root/.kube/config
  script:
    - echo "Loading the IMAGE_TAG from .env"
    - source .env  # This loads the IMAGE_TAG from the .env artifact
    - echo "Deploying backend with image tag ${IMAGE_TAG}"
    - envsubst < ./manifest.yaml | kubectl apply -f -
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"

