apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: ui-${BRANCH}
data:
  PORT: "5050"
  ATLAS_URI: "mongodb://root:gFsnkNhbMt@mongodb.ui-${BRANCH}.svc.cluster.local:27017/employees"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  namespace: ui-${BRANCH}
  labels:
    app: backend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: backend-app-container
        image: "akesosk.azurecr.io/akeso/backend-${BRANCH}:${IMAGE_TAG}"  # Dynamic image tag
        ports:
        - containerPort: 5050
        envFrom:
        - configMapRef:
            name: backend-config  # Using ConfigMap instead of Secret
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /record
            port: 5050
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /record
            port: 5050
          initialDelaySeconds: 5
          periodSeconds: 5
      imagePullSecrets:
      - name: acr-registry2  # Using the secret to pull the image from the private registry-1




---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: ui-${BRANCH}
spec:
  selector:
    app: backend-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5050
  type: ClusterIP
