apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: ui-dev-${BRANCH}
data:
  PORT: "5050"

---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: ui-dev-${BRANCH}
type: Opaque
data:
  ATLAS_URI: bW9uZ29kYjovL2VtcGxveWVlVXNlcjpFbVBsT3lFRUAxMjNAbW9uZ29kYi11aS1kZXY6MjcwMTcvZW1wbG95ZWVzCg==


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  namespace: ui-dev-${BRANCH}
  labels:
    app: backend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: backend-app-container
        image: "akesosk.azurecr.io/akeso/backend-dev:${IMAGE_TAG}"  # Dynamic image tag
        ports:
        - containerPort: 5050
        envFrom:
        - configMapRef:
            name: backend-config
        - secretRef:
            name: backend-secret
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /record
            port: 5050
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /record
            port: 5050
          initialDelaySeconds: 5
          periodSeconds: 5
      imagePullSecrets:
      - name: acr-registry2  # Using the secret to pull the image from the private registry



---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  namespace: ui-dev-${BRANCH}
spec:
  selector:
    app: backend-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5050
  type: NodePort
